services:
  - type: web
    name: gemini-tg-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        generateValue: true
      - key: GEMINI_MODEL
        value: gemini-2.5-pro
